# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='posted_date',
        ),
    ]
